// ===| Site Specific User Agent Overrides |======
// Force youtube to present the old style layout
pref("general.useragent.override.youtube.com","Mozilla/5.0 (Linux; Android 7.0; Mobile; rv:38.0) Gecko/38.0");

// ============================================================================
// Spoof the useragent and platform to a generic one for user experience and privacy
// pref("general.useragent.override", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:38.9) Gecko/20100101 Firefox/38.9 Arcticfox/38.9");
// pref("general.appname.override", "Netscape");
// pref("general.appversion.override", "5.0 (Windows)");
// pref("general.buildID.override", "Gecko/20100101");
// pref("general.oscpu.override", "Windows NT 10.0");
// pref("general.platform.override", "Win64");
