$inherits:
  from: 'tasks/builds/b2g_desktop_base.yml'
  variables:
    build_type: 'debug'

task:
  scopes:
      - 'docker-worker:cache:build-b2g-desktop-objects-debug'

  payload:
    cache:
        build-b2g-desktop-objects-debug: '/home/worker/object-folder'

  extra:
    treeherder:
      collection:
        debug: true

  payload:
    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/debug'
