$inherits:
  from: 'tasks/build.yml'
task:
  metadata:
    name: "[TC] B2G Desktop {{build_type}}"
    description: B2G Desktop {{build_type}}

  workerType: b2gbuild-desktop
  scopes:
    - 'docker-worker:cache:sources-gecko'
    - 'docker-worker:cache:sources-gaia'

  payload:
    cache:
      sources-gaia: '/home/worker/gaia'
      sources-gecko: '/home/worker/gecko'

    env:
      MOZCONFIG: 'b2g/config/mozconfigs/linux64_gecko/nightly'
      MOZTT_GIT_URL: '{{moztt_git_url}}'
      MOZTT_REVISION: '{{moztt_revision}}'

    command:
      - bin/build-b2g-desktop.sh

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      machine:
        platform: b2g-linux64

    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      tests: 'public/build/target.tests.zip'
