$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
task:
  workerType: emulator-kk-debug
  scopes:
    - 'docker-worker:cache:build-emulator-kk-debug'
  metadata:
    name: '[TC] B2G Emulator KK Debug'

  extra:
    treeherder:
      collection:
        debug: true
      machine:
        platform: b2g-emu-kk

  payload:
    cache:
      build-emulator-jb-debug: /home/worker/object-folder
    env:
      TARGET: 'emulator-kk'
      B2G_DEBUG: 1
