$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
task:
  workerType: emulator-kk
  scopes:
    - 'docker-worker:cache:build-emulator-kk-opt'
  metadata:
    name: '[TC] B2G KK Emulator Opt'

  extra:
    treeherder:
      machine:
        platform: b2g-emu-kk

  payload:
    cache:
      build-emulator-kk-opt: /home/worker/object-folder
    env:
      TARGET: 'emulator-kk'

