$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
task:
  workerType: emulator-ics
  scopes:
    - 'docker-worker:cache:build-emulator-ics-opt'
  metadata:
    name: '[TC] B2G Emulator ICS Opt'

  extra:
    treeherder:
      machine:
        platform: b2g-emu-ics

  payload:
    cache:
      build-emulator-ics-opt: /home/worker/object-folder/

    env:
      TARGET: 'emulator'

