$inherits:
  from: 'tasks/builds/b2g_emulator_base.yml'
task:
  workerType: emulator-ics-debug
  scopes:
    - 'docker-worker:cache:build-emulator-ics-debug'
  metadata:
    name: '[TC] B2G Emulator ICS Debug'
  extra:
    treeherder:
      collection:
        debug: true
      machine:
        platform: b2g-emu-ics


  payload:
    cache:
      build-emulator-ics-debug: /home/worker/object-folder
    env:
      TARGET: 'emulator'
      B2G_DEBUG: 1
