$inherits:
  from: 'tasks/build.yml'
task:
  metadata:
    name: '[TC] Mulet Linux x64 Opt'
    description: Mulet Linux x64 Opt

  workerType: b2gbuild-desktop
  scopes:
    - 'docker-worker:cache:sources-gecko'
    - 'docker-worker:cache:build-mulet-linux-objects'
    - 'docker-worker:cache:tooltool-cache'

  payload:
    cache:
      sources-gecko: '/home/worker/gecko'
      build-mulet-linux-objects: '/home/worker/object-folder'
      tooltool-cache: '/home/worker/tools/tooltool-cache'

    env:
      MOZCONFIG: 'b2g/dev/config/mozconfigs/linux64/mulet'

    maxRunTime: 3600

    command:
      - bin/build-mulet-linux.sh

  extra:
    treeherder:
      machine:
        platform: mulet-linux64
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.linux-x86_64.tar.bz2'
      tests: 'public/build/target.tests.zip'
