/* Automatically generated by 10.4Fx builder */

#if defined(TENFOURBIRD_TUNED)
#define STR_104(s) #s
#define XSTR_104(s) STR_104(s)
#define FX104_OPTIMIZED_FOR XSTR_104(TENFOURBIRD_TUNED) " Arcticfox"
#else
#define FX104_OPTIMIZED_FOR "PowerPC"
#endif